binder: Promote binder_[return|command]_strings out of CONFIG_ANDROID_BINDER_LOGS
binder_return_strings and binder_command_strings are two arrays that are of constant char pointers that are actually needed for binder tracing as we have CONFIG_FTRACE enabled.

Compiling it out throws the following compilation errors:

In file included from ../drivers/android/binder.c:6524:
In file included from ../drivers/android/./binder_trace.h:414:
In file included from ../include/trace/define_trace.h:96:
In file included from ../include/trace/trace_events.h:394:
../drivers/android/./binder_trace.h:387:40: error: use of undeclared identifier 'binder_command_strings'
                  _IOC_NR(__entry->cmd) < ARRAY_SIZE(binder_command_strings) ?
                                                     ^
../drivers/android/./binder_trace.h:387:40: error: use of undeclared identifier 'binder_command_strings'
../drivers/android/./binder_trace.h:387:40: error: use of undeclared identifier 'binder_command_strings'
../drivers/android/./binder_trace.h:388:6: error: use of undeclared identifier 'binder_command_strings'
                          binder_command_strings[_IOC_NR(__entry->cmd)] :
                          ^
../drivers/android/./binder_trace.h:403:40: error: use of undeclared identifier 'binder_return_strings'
                  _IOC_NR(__entry->cmd) < ARRAY_SIZE(binder_return_strings) ?
                                                     ^
../drivers/android/./binder_trace.h:403:40: error: use of undeclared identifier 'binder_return_strings'
../drivers/android/./binder_trace.h:403:40: error: use of undeclared identifier 'binder_return_strings'
../drivers/android/./binder_trace.h:404:6: error: use of undeclared identifier 'binder_return_strings'
                          binder_return_strings[_IOC_NR(__entry->cmd)] :
                          ^

Therefore, move both of the arrays out of CONFIG_ANDROID_BINDER_LOGS.

Fixes: a415f8f80e1 ("binder: Conditionally compile logging")
Signed-off-by: Tashfin Shakeer Rhythm <tashfinshakeerrhythm@gmail.com>
Signed-off-by: Pulkit077 <pulkitagarwal2k1@gmail.com>