cpu-boost: convert powerkey boost to new setup
Required after commit 3357c4a32213e.

../drivers/cpufreq/cpu-boost.c:306:21: error: use of undeclared identifier 'cpu_boost_wq'
  306 |         queue_delayed_work(cpu_boost_wq, &input_boost_rem,
      |                            ^
../drivers/cpufreq/cpu-boost.c:326:14: error: use of undeclared identifier 'cpu_boost_wq'
  326 |                 queue_work(cpu_boost_wq, &powerkey_input_boost_work);
      |                            ^
2 errors generated.

Signed-off-by: Flopster101 <nahuelgomez329@gmail.com>