cpufreq: schedutil: add rq for Uclamp
uclamp_util_with requires this parameter.

../kernel/sched/cpufreq_schedutil.c:245:30: error: use of undeclared identifier 'rq'
  245 |         *util = uclamp_util_with(rq, *util, NULL);
      |                                  ^
2 errors generated.

Signed-off-by: Flopster101 <nahuelgomez329@gmail.com>