power: smb5: drop duplicate POWER_SUPPLY_PROP_CHARGE_FULL_DESIGN case
This was added by CLO on a newer tag than what the Xiaomi changes were based on.

Though it's important to note that the Xiaomi change forces the capacity to 4000mAh, while the CLO change gets it from the BMS. This might need to be investiagated later.

../drivers/power/supply/qcom/qpnp-smb5.c:1880:7: error: duplicate case value 'POWER_SUPPLY_PROP_CHARGE_FULL_DESIGN'
 1880 |         case POWER_SUPPLY_PROP_CHARGE_FULL_DESIGN:
      |              ^
../drivers/power/supply/qcom/qpnp-smb5.c:1869:7: note: previous case defined here
 1869 |         case POWER_SUPPLY_PROP_CHARGE_FULL_DESIGN:
      |              ^
1 error generated.

Signed-off-by: Nahuel Gómez <nahuelgomez329@gmail.com>