usb: dwc3/gadget: fix duplicate case
The ACK merge introduced a duplicate case.

../drivers/usb/dwc3/gadget.c:2007:7: error: duplicate case value 'DWC3_LINK_STATE_U1'
 2007 |         case DWC3_LINK_STATE_U1:
      |              ^
../drivers/usb/dwc3/gadget.c:2004:7: note: previous case defined here
 2004 |         case DWC3_LINK_STATE_U1:
      |              ^
1 error generated.

Signed-off-by: Flopster101 <nahuelgomez329@gmail.com>