Revert "Bluetooth: hci_event: Fix sending MGMT_EV_DEVICE_FOUND for invalid address"
Not applicable.

../net/bluetooth/hci_event.c:4945:8: error: use of undeclared identifier 'ext_adv'; did you mean 'next_arg'?
 4945 |                 if (!ext_adv && (type == LE_ADV_IND ||
      |                      ^~~~~~~
      |                      next_arg
../include/linux/kernel.h:474:14: note: 'next_arg' declared here
  474 | extern char *next_arg(char *args, char **param, char **val);
      |              ^
../net/bluetooth/hci_event.c:4945:8: warning: address of function 'next_arg' will always evaluate to 'true' [-Wpointer-bool-conversion]
 4945 |                 if (!ext_adv && (type == LE_ADV_IND ||
      |                     ~^~~~~~~
../net/bluetooth/hci_event.c:4945:8: note: prefix with the address-of operator to silence this warning
 4945 |                 if (!ext_adv && (type == LE_ADV_IND ||
      |                      ^
      |                      &
1 warning and 1 error generated.

This reverts commit 6445fcbfd53996136c320a42ab5902bec7712803.

Signed-off-by: Flopster101 <nahuelgomez329@gmail.com>