pinctrl: msm: fix wakeup reason call
The function got renamed in 8c29afa601389, so fix the usage of it here.

../drivers/pinctrl/qcom/pinctrl-msm.c:2059:4: error: implicit declaration of function 'log_wakeup_reason' [-Werror,-Wimplicit-function-declaration]
 2059 |                         log_wakeup_reason(irq); /*Add-HMI_M516_A01-51*/
      |                         ^
../drivers/pinctrl/qcom/pinctrl-msm.c:2059:4: note: did you mean 'log_irq_wakeup_reason'?
../include/linux/wakeup_reason.h:24:6: note: 'log_irq_wakeup_reason' declared here
   24 | void log_irq_wakeup_reason(int irq);
      |      ^
1 error generated.

Signed-off-by: Nahuel Gómez <nahuelgomez329@gmail.com>