Revert "dm verity: skip verity work on I/O errors when system is shutting down"
This commit was already picked before and got picked again during a merge, causing a duplicate function:

../drivers/md/dm-verity-target.c:592:20: error: redefinition of 'verity_is_system_shutting_down'
  592 | static inline bool verity_is_system_shutting_down(void)
      |                    ^
../drivers/md/dm-verity-target.c:68:20: note: previous definition is here
   68 | static inline bool verity_is_system_shutting_down(void)
      |                    ^
1 error generated.

This reverts commit eda3eca1b36dd0b68e5442121056b02eb52c8672.

Signed-off-by: Flopster101 <nahuelgomez329@gmail.com>