fs: f2fs: remove duplicate definitions
Upstream and Xiaomi's commits added these at the same time, causing duplicate definitions.

../fs/f2fs/xattr.c:46:14: error: redefinition of 'xattr_alloc'
   46 | static void *xattr_alloc(struct f2fs_sb_info *sbi, int size, bool *is_inline)
      |              ^
../fs/f2fs/xattr.c:27:14: note: previous definition is here
   27 | static void *xattr_alloc(struct f2fs_sb_info *sbi, int size, bool *is_inline)
      |              ^
../fs/f2fs/xattr.c:56:13: error: redefinition of 'xattr_free'
   56 | static void xattr_free(struct f2fs_sb_info *sbi, void *xattr_addr,
      |             ^
../fs/f2fs/xattr.c:37:13: note: previous definition is here
   37 | static void xattr_free(struct f2fs_sb_info *sbi, void *xattr_addr,
      |             ^
2 errors generated.

Signed-off-by: Nahuel Gómez <nahuelgomez329@gmail.com>