[HACK] Makefile: Workaround techpack header files being copied to the wrong place
When building the kernel with a ROM like RvOS, an error like this will appear:

In file included from vendor/qcom/opensource/audio-hal/primary-hal/hal/audio_extn/sndmonitor.c:60:
In file included from vendor/qcom/opensource/audio-hal/primary-hal/hal/audio_extn/audio_extn.h:45:
vendor/qcom/opensource/audio-hal/primary-hal/hal/platform_api.h:22:10: fatal error: 'sound/voice_params.h' file not found
\#include <sound/voice_params.h>
         ^~~~~~~~~~~~~~~~~~~~~~
1 error generated.
05:38:07 ninja failed with: exit status 1

This happens because this file (and others from the same folder) get
installed to usr/include/audio/include/uapi/sound/ instead of
usr/include/sound/, which is what the HAL is looking for.

This commit introduces a very hacky workaround to allow specifically
telling the build system to copy the headers where they should be, and
it also prevents Makefile.headerinst from deleting ofter headers during
installation by filtering those out.

Signed-off-by: Flopster101 <nahuelgomez329@gmail.com>