Revert "net_sched: cls_flow: validate TCA_FLOW_RSHIFT attribute"
We don't have the NLA_POLICY_MAX function from upstream, so this doesn't work.

../net/sched/cls_flow.c:364:22: error: implicit declaration of function 'NLA_POLICY_MAX' [-Werror,-Wimplicit-function-declaration]
  364 |         [TCA_FLOW_RSHIFT]       = NLA_POLICY_MAX(NLA_U32,
      |                                   ^
../net/sched/cls_flow.c:364:22: warning: suggest braces around initialization of subobject [-Wmissing-braces]
  364 |         [TCA_FLOW_RSHIFT]       = NLA_POLICY_MAX(NLA_U32,
      |                                   ^~~~~~~~~~~~~~~~~~~~~~~
      |                                   {
  365 |                                                  31 /* BITS_PER_U32 - 1 */),
      |                                                  ~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                                                                            }
../net/sched/cls_flow.c:364:22: error: initializer element is not a compile-time constant
  364 |         [TCA_FLOW_RSHIFT]       = NLA_POLICY_MAX(NLA_U32,
      |                                   ^~~~~~~~~~~~~~~~~~~~~~~
  365 |                                                  31 /* BITS_PER_U32 - 1 */),
      |                                                  ~~~~~~~~~~~~~~~~~~~~~~~~~~
1 warning and 2 errors generated.

This reverts commit 1bf98464da5bc856d258adc95fbd1bea54ace6ff.