usb: gadget: fix duplicate case
The ACK merge introduced a duplicate case.

../drivers/usb/gadget/function/f_fs.c:1410:8: error: duplicate case value 'USB_SPEED_SUPER_PLUS'
 1410 |                 case USB_SPEED_SUPER_PLUS:
      |                      ^
../drivers/usb/gadget/function/f_fs.c:1408:8: note: previous case defined here
 1408 |                 case USB_SPEED_SUPER_PLUS:
      |

Signed-off-by: Flopster101 <nahuelgomez329@gmail.com>