resukisu: kpm: use thread_pid instead of pids[PIDTYPE_PID].pid
We have the backports to allow this, and it causes an error with the old
model.

../drivers/sukisu/kernel/kpm/super_access.c:152:28: error: no member named 'pids' in 'struct task_struct'
  152 | DEFINE_MEMBER(task_struct, pids[PIDTYPE_PID].pid)
      | ~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~
../drivers/sukisu/kernel/kpm/super_access.c:54:49: note: expanded from macro 'DEFINE_MEMBER'
   54 |       .size = sizeof(((struct struct_name *)0)->member),                                                               \
      |                      ~~~~~~~~~~~~~~~~~~~~~~~~~  ^
../drivers/sukisu/kernel/kpm/super_access.c:152:1: error: no member named 'pids' in 'task_struct'
  152 | DEFINE_MEMBER(task_struct, pids[PIDTYPE_PID].pid)
      | ^                          ~~~~
../drivers/sukisu/kernel/kpm/super_access.c:55:17: note: expanded from macro 'DEFINE_MEMBER'
   55 |       .offset = offsetof(struct struct_name, member) },
      |                 ^                            ~~~~~~
../include/linux/stddef.h:17:32: note: expanded from macro 'offsetof'
   17 | #define offsetof(TYPE, MEMBER)  __compiler_offsetof(TYPE, MEMBER)
      |                                 ^                         ~~~~~~
../include/linux/compiler-gcc.h:190:2: note: expanded from macro '__compiler_offsetof'
  190 |         __builtin_offsetof(a, b)
      |         ^                     ~
../drivers/sukisu/kernel/kpm/super_access.c:170:1: error: invalid application of 'sizeof' to an incomplete type 'struct DynamicStructMember[]'
  170 | DYNAMIC_STRUCT_END(task_struct)
      | ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../drivers/sukisu/kernel/kpm/super_access.c:61:75: note: expanded from macro 'DYNAMIC_STRUCT_END'
   61 |                                                            .count = sizeof(struct_name##_members) /                    \
      |                                                                           ^~~~~~~~~~~~~~~~~~~~~~~
3 errors generated.

Signed-off-by: Flopster101 <nahuelgomez329@gmail.com>