Revert "configs: trinket: Enable CONFIG_CGROUP_NET_PRIO"
Broken after qcom_sm8150 merge.

In file included from ../init/do_mounts.c:32:
In file included from ../include/linux/nfs_fs.h:31:
In file included from ../include/linux/sunrpc/clnt.h:28:
In file included from ../include/net/ipv6.h:16:
In file included from ../include/linux/ipv6.h:87:
In file included from ../include/linux/tcp.h:23:
In file included from ../include/net/sock.h:51:
In file included from ../include/linux/netdevice.h:46:
../include/net/netprio_cgroup.h:35:21: error: no member named 'id' in 'struct cgroup'
   35 |         idx = css->cgroup->id;
      |               ~~~~~~~~~~~  ^
1 error generated.

This reverts commit 860be658909ab0278bac858b5f3bb788bfcf525c.

Signed-off-by: Flopster101 <nahuelgomez329@gmail.com>